"""adicao da coluna vip

Revision ID: 238a4dea02e1
Revises: 247f875a8444
Create Date: 2025-06-24 19:13:41.577155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238a4dea02e1'
down_revision: Union[str, Sequence[str], None] = '247f875a8444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vip', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'vip')
    # ### end Alembic commands ###
