"""criacao_tabela_users

Revision ID: 247f875a8444
Revises: 
Create Date: 2025-06-24 19:00:09.387891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '247f875a8444'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=70), nullable=False),
                    sa.Column('last_name', sa.String(length=70), nullable=False),
                    sa.Column('password', sa.String(length=70), nullable=False),
                    sa.Column('birthday', sa.Date(), nullable=False),
                    sa.Column('email', sa.String(length=70), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # op.drop_table('users')

